# -*- coding: utf-8 -*-
"""Special Topics Assignment 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Cl7ENvocjVuzJGqizfAlEXXhYf7MqgG
"""

import google.generativeai as genai
GOOGLE_API_KEY = 'AIzaSyAppeMLq0ZIkSpPTCm0aDRnYJiX8h3nfug'
genai.configure(api_key=GOOGLE_API_KEY)

for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)

model = genai.GenerativeModel('gemini-pro')
chat = model.start_chat(history=[])
chat

"""Introduction:
Reflect on a specific experience in your life that you are particularly grateful for. This could be an event, a journey, a milestone, or any significant moment that has had a positive impact on you. Use the steps below to guide your reflection and expression of gratitude.

**Identify the Experience**
"""

response = chat.send_message("Think about an experience that stands out in your life as particularly meaningful and positive. This could be a memorable trip, a significant achievement, a special event, or a personal milestone. Explain briefly in 3-4 lines")
to_markdown(response.text)

"""**Describe the Experience**"""

response = chat.send_message("Provide a detailed description of the experience. Include where and when it took place, who was involved, and what happened.", stream=True)

for chunk in response:
  print(chunk.text)

"""**Explain Its Significance**"""

response = chat.send_message("Reflect on why this experience is important to you. Describe how it has impacted your life, what you learned from it, and how it has helped you grow as a person", stream=True)

for chunk in response:
  print(chunk.text)

"""**Express Your Gratitude**"""

response = chat.send_message("Write a heartfelt message expressing your gratitude for this experience. Focus on the positive impact it has had on your life and why you are thankful for it", stream=True)

for chunk in response:
  print(chunk.text)

"""**Highlight a Memorable Moment**"""

response = chat.send_message("Share a specific moment or event from this experience that stands out to you. Describe what happened, why it is memorable, and how it encapsulates the essence of the experience.", stream=True)

for chunk in response:
  print(chunk.text)

"""**Describe Its Long-term Impact**"""

response = chat.send_message("Reflect on the long-term impact this experience has had on your life. Consider how it continues to influence you today and how it might shape your future", stream=True)

for chunk in response:
  print(chunk.text)

"""**Connect to Personal Values**"""

response = chat.send_message("Think about how this experience aligns with your core personal values. Describe which values were reinforced or discovered through this experience and how they have shaped your worldview", stream=True)

for chunk in response:
  print(chunk.text)

"""**Acknowledge Challenges and Growth**"""

response = chat.send_message("Reflect on any challenges or difficulties you faced during this experience. Explain how overcoming these challenges contributed to your personal growth and resilience.", stream=True)

for chunk in response:
  print(chunk.text)

"""**Express Gratitude to Others Involved**"""

response = chat.send_message(" Identify any individuals who played a key role in making this experience possible or meaningful. Write a note of gratitude to these individuals, acknowledging their contributions and support.", stream=True)

for chunk in response:
  print(chunk.text)

"""**Share the Ripple Effect**"""

response = chat.send_message("Describe any ripple effects this experience has had on your life and the lives of others. Consider how the lessons and insights gained from this experience have influenced your actions and decisions, and how they might have impacted those around you", stream=True)

for chunk in response:
  print(chunk.text)

"""**Summarizing Gratitude Responses**"""

response = chat.send_message("Review your responses to the previous prompts. Identify the key points from each response, including the person involved, the impact of the experience, memorable moments, long-term effects, challenges overcome, and the support received", stream=True)

for chunk in response:
  print(chunk.text)

response = chat.send_message("Organize these key points into a cohesive narrative. Ensure that the message flows logically and connects the different aspects of your gratitude into one comprehensive expression", stream=True)

for chunk in response:
  print(chunk.text)

response = chat.send_message("Write a paragraph that encapsulates your overall gratitude for the experience, highlighting its significance and the positive impact it has had on your life", stream=True)

for chunk in response:
  print(chunk.text)

response = chat.send_message("End your summary with a final statement of gratitude, reiterating the importance of this experience and its lasting impact on your life", stream=True)

for chunk in response:
  print(chunk.text)